In [1]:
import numpy as np
import pandas as pd
from fuzzywuzzy import fuzz

C:\Users\rsure\AppData\Local\Continuum\anaconda3\lib\site-packages\fuzzywuzzy\fuzz.py:11: UserWarning: Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning
  warnings.warn('Using slow pure-python SequenceMatcher. Install python-Levenshtein to remove this warning')

In [2]:
df1 = pd.read_csv('HG Data.csv')
df2 = pd.read_csv('CRT_DNB.csv')

In [3]:
df1.head()

,Product Hit ID,DUNSNUMBER,VENDOR,Product ID,PRODUCT,Date First Verified,Date Last Verified,INTENSITY,Category Parent,CATEGORY,...,PHONE,URL,REVENUE,EMPLOYEES,SIC2,SIC2 Description,SIC3,SIC3 Description,SIC4,SIC4 Description
0,37888914,8129967,Microsoft Corporation,12416,Skype,2016-04-28 00:00:00.000,2020-06-12 00:00:00.000,20,Productivity Solutions,Collaboration,...,9564286666,reddyice.com,0,0,20,Food and Kindred Products,209,Miscellaneous Food And Kindred Products,2097,Manufactured ice
1,37888618,8249496,"Adobe, Inc.",791,Adobe (Unspecified Product),2019-04-23 00:00:00.000,2019-06-11 00:00:00.000,5,Productivity Solutions,Visualization Software,...,7173064272,salvationarmy.org,0,0,80,Health Services,805,Nursing And Personal Care Facilities,8052,Intermediate care facilities
2,37889109,8249496,Microsoft Corporation,562,Microsoft Office,2020-03-03 00:00:00.000,2020-05-03 00:00:00.000,8,Productivity Solutions,Productivity Solutions,...,7173064272,salvationarmy.org,0,0,80,Health Services,805,Nursing And Personal Care Facilities,8052,Intermediate care facilities
3,37888991,8249496,Microsoft Corporation,628,Microsoft PowerPoint,2020-03-03 00:00:00.000,2020-05-03 00:00:00.000,8,Productivity Solutions,Visualization Software,...,7173064272,salvationarmy.org,0,0,80,Health Services,805,Nursing And Personal Care Facilities,8052,Intermediate care facilities
4,37888546,8167627,"Autodesk, Inc.",94,AutoCAD,2011-08-01 00:00:00.000,2017-03-01 00:00:00.000,5,Productivity Solutions,Visualization Software,...,5703744813,sse-llc.com,438911,6,87,Engineering Accounting Research Management and...,871,Engineering And Architectural Services,8711,Engineering services

In [4]:
df1.columns

Index(['Product Hit ID', 'DUNSNUMBER', 'VENDOR', 'Product ID', 'PRODUCT',
       'Date First Verified', 'Date Last Verified', 'INTENSITY',
       'Category Parent', 'CATEGORY', 'ATTRIBUTES', 'Location Type', 'COMPANY',
       'ADDRESS', 'CITY', 'STATE', 'ZIP', 'COUNTRY', 'PHONE', 'URL', 'REVENUE',
       'EMPLOYEES', 'SIC2', 'SIC2 Description', 'SIC3', 'SIC3 Description',
       'SIC4', 'SIC4 Description'],
      dtype='object')

In [5]:
df1['RowNum'] = np.arange(len(df1))

In [6]:
df1

,Product Hit ID,DUNSNUMBER,VENDOR,Product ID,PRODUCT,Date First Verified,Date Last Verified,INTENSITY,Category Parent,CATEGORY,...,URL,REVENUE,EMPLOYEES,SIC2,SIC2 Description,SIC3,SIC3 Description,SIC4,SIC4 Description,RowNum
0,37888914,8129967,Microsoft Corporation,12416,Skype,2016-04-28 00:00:00.000,2020-06-12 00:00:00.000,20,Productivity Solutions,Collaboration,...,reddyice.com,0,0,20,Food and Kindred Products,209,Miscellaneous Food And Kindred Products,2097,Manufactured ice,0
1,37888618,8249496,"Adobe, Inc.",791,Adobe (Unspecified Product),2019-04-23 00:00:00.000,2019-06-11 00:00:00.000,5,Productivity Solutions,Visualization Software,...,salvationarmy.org,0,0,80,Health Services,805,Nursing And Personal Care Facilities,8052,Intermediate care facilities,1
2,37889109,8249496,Microsoft Corporation,562,Microsoft Office,2020-03-03 00:00:00.000,2020-05-03 00:00:00.000,8,Productivity Solutions,Productivity Solutions,...,salvationarmy.org,0,0,80,Health Services,805,Nursing And Personal Care Facilities,8052,Intermediate care facilities,2
3,37888991,8249496,Microsoft Corporation,628,Microsoft PowerPoint,2020-03-03 00:00:00.000,2020-05-03 00:00:00.000,8,Productivity Solutions,Visualization Software,...,salvationarmy.org,0,0,80,Health Services,805,Nursing And Personal Care Facilities,8052,Intermediate care facilities,3
4,37888546,8167627,"Autodesk, Inc.",94,AutoCAD,2011-08-01 00:00:00.000,2017-03-01 00:00:00.000,5,Productivity Solutions,Visualization Software,...,sse-llc.com,438911,6,87,Engineering Accounting Research Management and...,871,Engineering And Architectural Services,8711,Engineering services,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,37889188,8344702,Microsoft Corporation,13349,Microsoft SQL Server 2005,2007-09-07 00:00:00.000,2017-07-25 00:00:00.000,70,Data Center Solutions,Database Management Software,...,t-mobile.com,0,0,48,Communications,481,Telephone Communication,4812,Radiotelephone communication,95
96,37889861,8344702,Microsoft Corporation,13350,Microsoft SQL Server 2008,2014-02-01 00:00:00.000,2016-12-01 00:00:00.000,4,Data Center Solutions,Database Management Software,...,t-mobile.com,0,0,48,Communications,481,Telephone Communication,4812,Radiotelephone communication,96
97,37889066,8344702,Microsoft Corporation,17650,Microsoft SQL Server Integration Services,2009-11-06 00:00:00.000,2009-11-12 00:00:00.000,6,Data Center Solutions,Database Management Software,...,t-mobile.com,0,0,48,Communications,481,Telephone Communication,4812,Radiotelephone communication,97
98,37888444,8344702,Microsoft Corporation,8449,Microsoft Transact-SQL,2005-10-01 00:00:00.000,2017-10-01 00:00:00.000,22,Data Center Solutions,Operating Systems & Computing Languages,...,t-mobile.com,0,0,48,Communications,481,Telephone Communication,4812,Radiotelephone communication,98
99,37889543,8344702,Microsoft Corporation,18965,Microsoft TypeScript,2016-09-01 00:00:00.000,2020-06-07 00:00:00.000,8,Data Center Solutions,Operating Systems & Computing Languages,...,t-mobile.com,0,0,48,Communications,481,Telephone Communication,4812,Radiotelephone communication,99

In [7]:
df2

,PARTY_NAME,PARTY_ADDRESS1,PARTY_CITY,PARTY_STATE
0,TATA COMMUNICATIONS,12708 RIATA VISTA CIR,AUSTIN,TX
1,US ARMY ARDEC,BLDG 64,PICATINNY ARSENSAL,NJ
2,WEST CENTRAL STEEL,10 19TH STREET NW,WILLMAR,MN
3,"LTF CLUB OPERATIONS COMPANY, INC.",11220 GOLF LINKS DRIVE,CHARLOTTE,NC
4,INDUSTRIAL TOOLS EXPORT,8770 W BRYN MAWR AVE,CHICAGO,IL
...,...,...,...,...
95,CANDLEWOOD SUITES,1855 S SILVERSTONE WAY,MERIDIAN,ID
96,DENTON COUNTY FRIENDS OF THE FAMILY,4845 N I-35E,DENTON,TX
97,CONNECTIVITY SOURCE,1720 W THOMAS ST,HAMMOND,LA
98,DOCTOR STEPHEN DENT,477 N EL CAMINO REAL,ENCINITAS,CA
99,CONNECTIVITY SOURCE,216 SAINT JAMES AVE,GOOSE CREEK,SC

In [8]:
def Mapping(x1,x2,x3,x4,x5,x6,x7,x8,x9):
    a=[]
    b=[]
    c=[]
    d=[]
    e=[]
    f=[]
    g=[]
    h=[]
    k=[]
    l=[]
    m=[]
    n=[]
    row=[]
    for i in x1:
        for j in x2:
            a.append(i)
            b.append(j)
            c.append(fuzz.token_sort_ratio(i,j))
    for i in x3:
        for j in x4:
            d.append(i)
            e.append(j)
            f.append(fuzz.token_sort_ratio(i,j))
    for i in x5:
        for j in x6:
            g.append(i)
            h.append(j)
            k.append(fuzz.token_sort_ratio(i,j))
    for i in x7:
        for j in x8:
            l.append(i)
            m.append(j)
            n.append(fuzz.token_sort_ratio(i,j))
        for i in x9:
            row.append(i)
    return a,b,c,d,e,f,g,h,k,l,m,n,row

def New_df(x1,x2,x3,x4,x5,x6,x7,x8,x9):
    Records = Mapping(x1,x2,x3,x4,x5,x6,x7,x8,x9)
    Records= np.array(Records).transpose().tolist()
    df_1 = pd.DataFrame(Records)
    df_1.columns = ['Company1','Comapny2','Company_Map','Satte1','State2','State_Map','City1','City2','City_Map',
                   'Addre1','Addre2','Add_Map','Row']
    return df_1

In [9]:
New_df(df1['COMPANY'],df2['PARTY_NAME'],df1['STATE'],df2['PARTY_STATE'],df1['CITY'],df2['PARTY_CITY'],df1['ADDRESS'],df2['PARTY_ADDRESS1'],df1['RowNum'])

,Company1,Comapny2,Company_Map,Satte1,State2,State_Map,City1,City2,City_Map,Addre1,Addre2,Add_Map,Row
0,Reddy Ice Corporation,TATA COMMUNICATIONS,40,TX,TX,100,Harlingen,AUSTIN,40,1409 N 28th St,12708 RIATA VISTA CIR,40,0
1,Reddy Ice Corporation,US ARMY ARDEC,18,TX,NJ,0,Harlingen,PICATINNY ARSENSAL,44,1409 N 28th St,BLDG 64,19,1
2,Reddy Ice Corporation,WEST CENTRAL STEEL,31,TX,MN,0,Harlingen,WILLMAR,25,1409 N 28th St,10 19TH STREET NW,65,2
3,Reddy Ice Corporation,"LTF CLUB OPERATIONS COMPANY, INC.",38,TX,NC,0,Harlingen,CHARLOTTE,56,1409 N 28th St,11220 GOLF LINKS DRIVE,33,3
4,Reddy Ice Corporation,INDUSTRIAL TOOLS EXPORT,32,TX,IL,0,Harlingen,CHICAGO,38,1409 N 28th St,8770 W BRYN MAWR AVE,29,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,"T-Mobile Usa, Inc.",CANDLEWOOD SUITES,36,GA,ID,0,Atlanta,MERIDIAN,27,85 5th St NW,1855 S SILVERSTONE WAY,29,95
9996,"T-Mobile Usa, Inc.",DENTON COUNTY FRIENDS OF THE FAMILY,31,GA,TX,0,Atlanta,DENTON,31,85 5th St NW,4845 N I-35E,50,96
9997,"T-Mobile Usa, Inc.",CONNECTIVITY SOURCE,17,GA,LA,50,Atlanta,HAMMOND,29,85 5th St NW,1720 W THOMAS ST,21,97
9998,"T-Mobile Usa, Inc.",DOCTOR STEPHEN DENT,23,GA,CA,50,Atlanta,ENCINITAS,38,85 5th St NW,477 N EL CAMINO REAL,25,98
9999,"T-Mobile Usa, Inc.",CONNECTIVITY SOURCE,17,GA,SC,0,Atlanta,GOOSE CREEK,0,85 5th St NW,216 SAINT JAMES AVE,32,99